### ISSUE TITLE
Research on rendering and deployment of 3d models using unity in the browser

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#1]
For a first comparison a project should be created which loads the provided 3d models of metr in unity. The application needs to be executable in the browser.

Furthermore, the performance of Unity in combination with WebGL should be researched.
Additionally, the availability of techniques such as occlusion culling and plane clipping should be examined.

**Comment by lnlytumbleweed** [comment]
**First Trail&Error:**

**Used Specs:**
- Unity (2018.2.16f1)
- Plugin: UniGLTF 1.27 (https://github.com/ousttrue/UniGLTF/releases)
- Build Settings: WebGL
- Used GLTF file: facility-mechanical-room
- Browser: Firefox

**Pro's:**
- Plugin is easy to use
- Rendered Objects looking great (see gif)

**Con's:**
- Performance issues: Plugin is loading the gltf-file super slow (20 min.) -> Maybe because of the **731 Meshes** for this specific gltf)
- Build in browser is lagging on my pc (maybe its because of my old macbook pro from 2011, but should be fine)

![FirstTest_Unity](https://user-images.githubusercontent.com/26483797/78871716-69d4a900-7a48-11ea-9949-aa6847e7ee7e.gif)


**Next:**

- [x] examine occlusion culling and plane clipping to see if we can improve the performance

**Comment by lnlytumbleweed** [comment]
**Performance boosting:**

**Occlusion Culling:** It makes only sense, when the Gameobjects are big. Because it is only rendering the parts, which the camera is actually seeing. But when you have a lot of detailed meshes near by (the gltf file has **6 Million Triangles (Polygons)** in total), the culling is not deleting a lot of stuff (see screenshots).

![Bildschirmfoto 2020-04-13 um 12 16 23](https://user-images.githubusercontent.com/26483797/79127602-79ceee80-7da2-11ea-949e-800297c135c8.png)

**Solution:** Make the Gltf-Gameobject bigger (Scale twice the size)

**Result:** The FPS (around 20) is better when you move the camera inside the building. When you're outside the building, the renderer renders everything (around 11 FPS). Here comes the **Clipping Plane** to action.

**Clipping Plane:** So the clipping plane cuts everything out, what is not in the view frustum. (You can adjust the near and far thresholds) I put it to 0.3 near and 100 far

**Result:** Almost 20 FPS also outside from the building

**Player Settings:** for WebGL in Unity (see screenshot) the **Prebake Collision Meshes** in player settings gives the application a bigger increase in performance, then the occlusion culling. To the disadvantage of the shader lights, they not looking dynamic anymore, they are also baked.

![Bildschirmfoto 2020-04-13 um 13 09 00](https://user-images.githubusercontent.com/26483797/79127511-50ae5e00-7da2-11ea-926d-f135913e7671.png)


**Artefacts:** Actually the Occlusion Culling does not delete every object behind the camera (see screenshot). Right know, I don't know why.

![Bildschirmfoto 2020-04-13 um 12 21 46](https://user-images.githubusercontent.com/26483797/79127531-5d32b680-7da2-11ea-990e-f3b5657fa24c.png)



All in all, Unity gives a bunch of adjustable parameters on your hand, and it is pretty easy to adjust them as well. But still, **20 FPS is not enough to run it smoothly.** We should test it with another PC also as a next step, because I have a really old laptop here.
