### ISSUE TITLE
As a user I want see a list of all the models to know which are available to view in 3d.

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#24]
When the user opens the website a list of all avaiable models should be presented. When the user selects one model he will be redirected to the 3d viewer (described in https://github.com/vi-sense/vi-sense/issues/22).

**Comment by lnlytumbleweed** [comment]
- [x] evaluating frameworks to fulfil the binding to Babylon / Models
- [x] set up initial start page
- [x] Binding to backend endpoints
- [x] Binding to frontend (Babylon)

**Comment by lnlytumbleweed** [comment]
### **evaluating frameworks to fulfil the binding to Babylon / Models**

Angular

- framework out of the box / a lot of functionalities  already in
- Comes with Typescript
- but not lightweight

Vue

- Simple, modern framework, which is lightweight
- easy to set up
- expandable with a lot of libraries

**Frontend team decided to use vue, because typescript is not necessary in the startpage of the frontend and experience reasons.**

**Comment by lnlytumbleweed** [comment]
### **set up initial start page**

https://github.com/vi-sense/vi-sense-frontend/tree/landingpage/vue-startpage/vue-spa

@dephiloper @RomanKrajewski: waiting for models-endpoint as **following example format**:  

```
id: {model-number}
title: {model-name}
desc: {model-description}
picture: {model-picture} 
// What do you think? Okish?
```

inspired by this json-file: https://jsonplaceholder.typicode.com/posts/

**Comment by dephiloper** [comment]
Endpoint documentation can be found here:
https://github.com/vi-sense/vi-sense/wiki/API

**Comment by lnlytumbleweed** [comment]
![Bildschirmfoto 2020-04-29 um 18 03 07](https://user-images.githubusercontent.com/26483797/80618484-bc035b80-8a43-11ea-830e-9cbc630e872c.png)
