### ISSUE TITLE
visualize anomalies inside babylon

### ISSUE THREAD

**Issue by dephiloper** [vi-sense/vi-sense#46]
* explore stuff like shaders, opacity, scale, animations, colors, ...

**Comment by grimmle** [comment]
# Shaders
I did some research on shaders in general and experimented with the Node Materials in Babylonjs.
The Node Material Editor is a great tool to create new materials or tweak ones alread created by others. 
    
This is a example i came up with: https://nme.babylonjs.com/#QPRJU9#16
It's basically a sine function mapped to certain color values. This basic blinking could be used to display the active state of pipes and valves.
![blinking](https://user-images.githubusercontent.com/52577845/82240793-4fd99080-993b-11ea-8555-1bd74a0bc91a.gif)

    
Another example using a sine function, but mapped to a gradient: https://nme.babylonjs.com/#QPRJU9#12
Could be used to display water flowing through pipes.
![flowing](https://user-images.githubusercontent.com/52577845/82240359-98447e80-993a-11ea-8b00-b05b3964ade8.gif)

    
I also found a existing shader using noise to create a fire effect: https://nme.babylonjs.com/#JN2BSF#54
For when things go wrong :D
![fire](https://user-images.githubusercontent.com/52577845/82240338-9084da00-993a-11ea-8901-c6ab36776efd.gif)

    
# Highlighting Methods
Highlight Layer
- displays glow around edges of selected mesh
\+ also shown through other meshes
\- glow is not that pretty

    
Outline
- simple outline drawn around the edges of a mesh
\- looks kind of weird at some angles
\- not that eyecatching; might get lost in bigger models

![highlight](https://user-images.githubusercontent.com/52577845/82242170-b1026380-993d-11ea-9657-8a022fb4bd09.gif)
(mix of outline and highlight layer)
    
Bounding Box
- show bounding box of selected mesh
\+ shown through other meshes when occluded
\- loses its value when the selected mesh is really big, because it doesnt really help to locate the mesh
<img width="1421" alt="boundingbox" src="https://user-images.githubusercontent.com/52577845/82241113-e017d580-993b-11ea-9521-cc8a5fbb6141.png">
